#!/bin/bash

COMP_ONLY=0

TESTNAME="playcontrol_tb"
DESIGN_FILES="  ../rtl/system_constants_pkg.vhd  \
                ../sim/playcontrol_tb.vhd        \
                ../rtl/playcontrol.vhd           \
                ../rtl/file_info_processor.vhd   \
                ../rtl/arbiter_mux.vhd           \
                ../rtl/list_ctrl.vhd             \
                ../rtl/play_fsm.vhd              \
                ../rtl/kbc_intf.vhd"

if [ -e work ]
then
  rm -r work
fi
vlib work

echo "Running VHDL Compilation ..."
echo "================================================================================"
VCOM_SWITCH_LIST=" -lint -novopt -quiet"
echo ">>" vlib work
echo ">>" vcom  $VCOM_SWITCH_LIST $DESIGN_FILES
vcom  $VCOM_SWITCH_LIST $DESIGN_FILES

if [ $? != 0 ]
then
  echo "§§§§§§§§§§§§§§§§ Compilation error §§§§§§§§§§§§§§§§";
  echo
  exit 0;
else
  echo "§§§§§§§§§§§§§§§§ Compilation successful §§§§§§§§§§§§§§§§";
  echo
fi

if [ $COMP_ONLY != 1 ]
then
  echo 'Running Simulation ...'
  echo "================================================================================"
  VSIM_SWITCH_LIST=" -novopt -quiet"
  echo ">>" vsim $VSIM_SWITCH_LIST -l $TESTNAME.log -wlf $TESTNAME.wlf work.$TESTNAME -do vsim.do
  vsim $VSIM_SWITCH_LIST -l $TESTNAME.log -wlf $TESTNAME.wlf work.$TESTNAME -do vsim.do

  # Checking for errors in $TESTNAME.log
  SIM_ERR=`grep -i error $TESTNAME.log | wc -l`
  if [ $SIM_ERR == 0 ]
  then
    echo "§§§§§§§§§§§§§§§§ Simulation passed §§§§§§§§§§§§§§§§";
  else
    echo "§§§§§§§§§§§§§§§§ Simulation failed with $SIM_ERR errors §§§§§§§§§§§§§§§§";
  fi
  echo "See $TESTNAME.log for details"
fi

# clean up temp files
# rm -r ./work
