#!/bin/bash

if [ $# -lt 1 ]
then
  echo "Usage: simulate SIMFILE"
  echo "SIMFILE must be specified."
  exit 1
fi

SIMFILE=$1
TESTNAME=${SIMFILE%.*}

if [ ! -f $SIMFILE ]
then
  echo "SIMFILE $SIMFILE doesn't exist."
  exit 1
fi

COMP_ONLY=0
CONSOLE=0

if [ $# -eq 2 ]
then
  if [ $2 = "-c" ];then
    COMP_ONLY=1
  fi

  if [ $2 = "-b" ];then
    CONSOLE=1
  fi
fi

DESIGN_FILES="  ../rtl/system_constants_pkg.vhd   \
                ../rtl/playcontrol.vhd            \
                ../rtl/file_info_processor.vhd    \
                ../rtl/arbiter_mux.vhd            \
                ../rtl/list_ctrl.vhd              \
                ../rtl/play_fsm.vhd               \
                ../rtl/monitor_fsm.vhd            \
                ../rtl/kbc_intf.vhd               \
                $SIMFILE"

# Adding compilation library
rm -rf work
vlib work

echo "%% Running VHDL Compilation ..."
VCOM_SWITCH_LIST=" -lint -novopt -quiet"
echo "%%" vlib work
echo "%%" vcom  $VCOM_SWITCH_LIST $DESIGN_FILES
vcom  $VCOM_SWITCH_LIST $DESIGN_FILES

if [ $? != 0 ]
then
  echo
  echo "%%%%%%%%%%% Compilation error %%%%%%%%%%%";
  echo
  exit 0;
else
  echo
  echo "%%%%%%%%%%% Compilation successful %%%%%%%%%%%";
  echo
fi

if [ $COMP_ONLY -ne 1 ]
then
  echo '%% Running Simulation ...'
  if [ $CONSOLE -eq 1 ]
  then
    VSIM_SWITCH_LIST=" -novopt -quiet -do vsim.do -c"
  else
    VSIM_SWITCH_LIST=" -novopt -quiet -do vsim.do"
  fi
  echo "%%" vsim work.sim $VSIM_SWITCH_LIST -l $TESTNAME.log -wlf $TESTNAME.wlf
  vsim work.sim $VSIM_SWITCH_LIST -l $TESTNAME.log -wlf $TESTNAME.wlf

  # Checking for errors in simulation report
  SIM_ERR=`grep -i error $TESTNAME.log | wc -l`
  if [ $SIM_ERR == 0 ]
  then
    echo
    echo "%%%%%%%%%%% Simulation passed %%%%%%%%%%%";
  else
    echo
    echo "%%%%%%%%%%% Simulation failed with $SIM_ERR errors %%%%%%%%%%%";
  fi
  echo "See $TESTNAME.log for details"
fi

# clean up temp files
rm -rf ./work
