#!/bin/bash

if [ $# -ne 1 ]
then
  echo "Usage: download_topsystem BITFILE"
  echo "BITFILE must be specified."
  exit 1
fi

if [ ! -f $BITFILE ]
then
  echo "BITFILE $BITFILE doesn't exist."
  exit 1
fi

CURRDIR=`pwd`
PRJDIR="$CURRDIR/../../top_system"
BITFILE=$CURRDIR/$1
BITFILE_NAME=${BITFILE##*/}
BITFILE_REV=${BITFILE_NAME#*.}
REV_LENGTH=`expr ${#BITFILE_REV} - 4`
BITFILE_REV=${BITFILE_REV:0:$REV_LENGTH}
REPORT=$CURRDIR/download.report.$BITFILE_REV

# Copy required bit file to project folder
mv -sf $PRJDIR/top_system.bit $PRJDIR/top_system.bit.orig
ln -sf $BITFILE $PRJDIR/top_system.bit

# Clean up older report
rm -f $REPORT
touch $REPORT

echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT
echo "%% Report generated on `date`" >> $REPORT
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT
echo >> $REPORT

# Run download processes from the ISE project folder
cd $PRJDIR

echo >> $REPORT
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT
echo "%% Running MP3download script ..." >> $REPORT
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT
./MP3download | tee -a $REPORT

# Restore original bitfile in project folder
mv -sf $PRJDIR/top_system.bit.orig $PRJDIR/top_system.bit

# Go back to current directory
cd $CURRDIR
