#!/bin/bash
export LD_LIBRARY_PATH=$XILINX/bin/lin

if [ $# -ne 1 ]
then
  echo "Usage: implement_topsystem BITFILE_REVISION"
  echo "BITFILE_REVISION must be given."
  exit 1
fi

CURRDIR=`pwd`
PRJDIR="../../top_system"
REPORT=$CURRDIR/implement.report
BITFILE_REV=$1

# Clean up older report
rm -f $REPORT
touch $REPORT

echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT
echo "%% Report generated on `date`" >> $REPORT
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT
echo >> $REPORT
echo >> $REPORT

# First synthesize playcontrol module in the current folder
echo >> $REPORT
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT
echo "%% Synthesizing playcontrol module..." >> $REPORT
echo "%% Process started at `date`" >> $REPORT
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT
./synthesize_playcontrol | tee -a $REPORT

echo >> $REPORT
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT
echo "%% Now rest of the processes will run for top_system..." >> $REPORT
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT


# Run implement processes from the ISE project folder
cd $PRJDIR

echo >> $REPORT
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT
echo "%% Running xst (Synthesis)..." >> $REPORT
echo "%% Process started at `date`" >> $REPORT
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT
xst -ise "/afs/regent.e-technik.tu-muenchen.de/home/rse31/rse31/prj/top_system/top_system.ise" -intstyle ise -ifn top_system.xst -ofn top_system.syr | tee -a $REPORT

echo >> $REPORT
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT
echo "%% Running ngdbuild (Translate)..." >> $REPORT
echo "%% Process started at `date`" >> $REPORT
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT
ngdbuild -ise "/afs/regent.e-technik.tu-muenchen.de/home/rse31/rse31/prj/top_system/top_system.ise" -intstyle ise -dd _ngo  -sd "../playcontrol/synthesis/" -sd "../ppc_ctrl" -sd "../ppc_core/implementation/" -sd "../ps2_kbc" -sd "../sysctrl" -sd "../test_modules" -nt timestamp -uc "top_system.ucf" -p xc2vp30-ff896-7 "top_system.ngc" top_system.ngd | tee -a $REPORT

echo >> $REPORT
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT
echo "%% Running map (Map)..." >> $REPORT
echo "%% Process started at `date`" >> $REPORT
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT
map -ise "/afs/regent.e-technik.tu-muenchen.de/home/rse31/rse31/prj/top_system/top_system.ise" -intstyle ise -p xc2vp30-ff896-7 -cm area -pr b -k 4 -c 100 -tx off -o top_system_map.ncd top_system.ngd top_system.pcf | tee -a $REPORT

echo >> $REPORT
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT
echo "%% Running par (Place and Route)..." >> $REPORT
echo "%% Process started at `date`" >> $REPORT
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT
par -ise "/afs/regent.e-technik.tu-muenchen.de/home/rse31/rse31/prj/top_system/top_system.ise" -w -intstyle ise -ol std -t 1 top_system_map.ncd top_system.ncd top_system.pcf | tee -a $REPORT

echo >> $REPORT
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT
echo "%% Running trce (TRACE)..." >> $REPORT
echo "%% Process started at `date`" >> $REPORT
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT
trce -ise "/afs/regent.e-technik.tu-muenchen.de/home/rse31/rse31/prj/top_system/top_system.ise" -intstyle ise -e 3 -s 7 -xml top_system top_system.ncd -o top_system.twr top_system.pcf -ucf top_system.ucf | tee -a $REPORT

echo >> $REPORT
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT
echo "%% Running bitgen (Bitfile generation)..." >> $REPORT
echo "%% Process started at `date`" >> $REPORT
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT
bitgen -ise "/afs/regent.e-technik.tu-muenchen.de/home/rse31/rse31/prj/top_system/top_system.ise" -intstyle ise -f top_system.ut top_system.ncd | tee -a $REPORT



echo >> $REPORT
echo >> $REPORT
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT
echo "%% All processes finished at `date`" >> $REPORT
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" >> $REPORT

# Copy bit file to current folder
cp -pf top_system.bit $CURRDIR/bitfiles/top_system.bit.$BITFILE_REV

# Copy report to project folder also
cd $CURRDIR
cp -pf $REPORT $PRJDIR
